### ISSUE TITLE
add support for a new dataset

### ISSUE THREAD

**Issue by uwmyuan** [nwojke/cosine_metric_learning#2]
Hi, Nicolai @nwojke 
Thank you for sharing the training code of deep_sort. 

I'm excited to read it and test it on another dataset. Specifically, I try to add [`train_sdd.py` and `sdd.py`](https://github.com/uwmyuan/cosine_metric_learning/commit/22d28d45eaeac828cc4dbae8d6c19d3ddffb385a) to use [the UAV dataset ](http://cvgl.stanford.edu/projects/uav_data/). 
The following training command is used to start training:
```
python train_sdd.py \
    --loss_mode=cosine-softmax \
    --log_dir=./output/sdd/ \
    --run_id=cosine-softmax
```
However, I got the following logging errors:
```
Train set size: 140670 images, 115 identities
feature dimensionality:  128
---------------------------------------
Run ID:  cosine-softmax
Log directory:  ./output/sdd/cosine-softmax
---------------------------------------
EnqueueError: Cannot feed value of shape (128, 128, 128, 3) for Tensor 'Placeholder_1:0', which has shape '(?,)'
```
and the following warnings:
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/yuan2/anaconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
OSError: [Errno 5] Input/output error
Call stack:
  File "train_sdd.py", line 141, in <module>
    main()
  File "train_sdd.py", line 82, in main
    **train_kwargs)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 188, in train_loop
    trainable_scopes=trainable_scopes)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 268, in create_trainer
    feature_var, logit_var = network_factory(image_var)
  File "/home/yuan2/cosine_metric_learning/nets/deep_sort/network_definition.py", line 120, in factory_fn
    weight_decay=weight_decay)
  File "/home/yuan2/cosine_metric_learning/nets/deep_sort/network_definition.py", line 84, in create_network
    features = tf.nn.l2_normalize(features, dim=1)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 315, in new_func
    instructions)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 118, in warning
    _get_logger().warning(msg, *args, **kwargs)
Message: 'From %s: calling %s (from %s) with %s is deprecated and will be removed %s.\nInstructions for updating:\n%s'
Arguments: ('/home/yuan2/cosine_metric_learning/nets/deep_sort/network_definition.py:84', 'l2_normalize', 'tensorflow.python.ops.nn_impl', 'dim', 'in a future version', 'dim is deprecated, use axis instead')
--- Logging error ---
Traceback (most recent call last):
  File "/home/yuan2/anaconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
OSError: [Errno 5] Input/output error
Call stack:
  File "train_sdd.py", line 141, in <module>
    main()
  File "train_sdd.py", line 82, in main
    **train_kwargs)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 188, in train_loop
    trainable_scopes=trainable_scopes)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 269, in create_trainer
    _create_loss(feature_var, logit_var, label_var, mode=loss_mode)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 643, in _create_loss
    _create_softmax_loss(feature_var, logit_var, label_var)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 615, in _create_softmax_loss
    logit_var, tf.cast(label_var, tf.int64))
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 135, in new_func
    instructions)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 118, in warning
    _get_logger().warning(msg, *args, **kwargs)
Message: 'From %s: %s (from %s) is deprecated and will be removed %s.\nInstructions for updating:\n%s'
Arguments: ('/home/yuan2/cosine_metric_learning/train_app.py:615', 'sparse_softmax_cross_entropy', 'tensorflow.contrib.losses.python.losses.loss_ops', 'after 2016-12-30', 'Use tf.losses.sparse_softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.')
--- Logging error ---
Traceback (most recent call last):
  File "/home/yuan2/anaconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
OSError: [Errno 5] Input/output error
Call stack:
  File "train_sdd.py", line 141, in <module>
    main()
  File "train_sdd.py", line 82, in main
    **train_kwargs)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 188, in train_loop
    trainable_scopes=trainable_scopes)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 269, in create_trainer
    _create_loss(feature_var, logit_var, label_var, mode=loss_mode)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 643, in _create_loss
    _create_softmax_loss(feature_var, logit_var, label_var)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 615, in _create_softmax_loss
    logit_var, tf.cast(label_var, tf.int64))
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py", line 435, in sparse_softmax_cross_entropy
    return compute_weighted_loss(losses, weights, scope=scope)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 135, in new_func
    instructions)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 118, in warning
    _get_logger().warning(msg, *args, **kwargs)
Message: 'From %s: %s (from %s) is deprecated and will be removed %s.\nInstructions for updating:\n%s'
Arguments: ('/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:435', 'compute_weighted_loss', 'tensorflow.contrib.losses.python.losses.loss_ops', 'after 2016-12-30', 'Use tf.losses.compute_weighted_loss instead.')
--- Logging error ---
Traceback (most recent call last):
  File "/home/yuan2/anaconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
OSError: [Errno 5] Input/output error
Call stack:
  File "train_sdd.py", line 141, in <module>
    main()
  File "train_sdd.py", line 82, in main
    **train_kwargs)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 188, in train_loop
    trainable_scopes=trainable_scopes)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 269, in create_trainer
    _create_loss(feature_var, logit_var, label_var, mode=loss_mode)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 643, in _create_loss
    _create_softmax_loss(feature_var, logit_var, label_var)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 615, in _create_softmax_loss
    logit_var, tf.cast(label_var, tf.int64))
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py", line 435, in sparse_softmax_cross_entropy
    return compute_weighted_loss(losses, weights, scope=scope)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py", line 152, in compute_weighted_loss
    add_loss(mean_loss)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 135, in new_func
    instructions)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 118, in warning
    _get_logger().warning(msg, *args, **kwargs)
Message: 'From %s: %s (from %s) is deprecated and will be removed %s.\nInstructions for updating:\n%s'
Arguments: ('/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:152', 'add_arg_scope.<locals>.func_with_args', 'tensorflow.contrib.losses.python.losses.loss_ops', 'after 2016-12-30', 'Use tf.losses.add_loss instead.')
--- Logging error ---
Traceback (most recent call last):
  File "/home/yuan2/anaconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
OSError: [Errno 5] Input/output error
Call stack:
  File "train_sdd.py", line 141, in <module>
    main()
  File "train_sdd.py", line 82, in main
    **train_kwargs)
  File "/home/yuan2/cosine_metric_learning/train_app.py", line 199, in train_loop
    save_interval_secs=save_interval_secs, number_of_steps=number_of_steps)
  File "/home/yuan2/cosine_metric_learning/queued_trainer.py", line 408, in run
    **kwargs)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 736, in train
    init_fn=init_fn)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 135, in new_func
    instructions)
  File "/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 118, in warning
    _get_logger().warning(msg, *args, **kwargs)
Message: 'From %s: %s (from %s) is deprecated and will be removed %s.\nInstructions for updating:\n%s'
Arguments: ('/home/yuan2/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py:736', 'Supervisor.__init__', 'tensorflow.python.training.supervisor', 'in a future version', 'Please switch to tf.train.MonitoredTrainingSession')
```

Could you help me? Thank you.

**Comment by alexanderfrey** [comment]
Did you find a solution to your problem yet ?

**Comment by nwojke** [comment]
Sorry for the late response. Lets see.. the error message indicates that the data that is placed in the training queue is of incorrect shape. This could either be the image/filename or the label tensor. 

Since the training images are passed to the train_app as filenames, ``read_from_file`` [here](https://github.com/nwojke/cosine_metric_learning/blob/master/train_app.py#L245) should evaluate to ``True`` and the ``filename_var`` in the following lines should be enqueued (this gives the shape ``(?,)``).

Now the data that is fed to the trainer seems to be images, as the shape is ``(128, 128, 128, 3)`` this can hardly be a filename.. Could you verify the type of ``train_x`` and ``train_y`` in line 72 of your code snippet and then, if this is a list of strings, call the ``feed_generator`` once [here](https://github.com/nwojke/cosine_metric_learning/blob/master/train_app.py#L190) to see if the returned data is images or strings? Something like this:

```
x, y = feed_generator()
print(x)
print(y)
```

**Comment by uwmyuan** [comment]
@nwojke Thanks for your kindly reply.
From your clue, I found...
(a) The original code doesn't include an array-type input. By default, `filenames` are a list of strings which are the names of image files. If the inputs are arrays, the type `filenames` should be `np.narray`. A [flag](https://github.com/nwojke/cosine_metric_learning/blob/ea25c8d402360a047a0750164b76dab131af9e42/train_app.py#L183) is produced to recognize the type of `train_x`.
(b) In my [variation](https://github.com/uwmyuan/cosine_metric_learning/blob/22d28d45eaeac828cc4dbae8d6c19d3ddffb385a/train_sdd.py#L28), the inputs are image arrays, but the type of `filenames` is `list`, which causes the error.
So, I modify the code to case `filenames` to `np.narray`.
Thanks

**Comment by nwojke** [comment]
This part of the code is indeed a bit fragile but looks like you got it working :+1:

**Comment by maylad31** [comment]
Hi, thanks for the code. Can I use it for msmt17 dataset?

**Comment by uwmyuan** [comment]
@maylad31 Thanks for your question. If you'd like to apply the code to any new dataset, you may like to test it because it does not fit EVERY dataset obviously.
