### ISSUE TITLE
About model export issue to deepsort

### ISSUE THREAD

**Issue by CindyHXH** [nwojke/cosine_metric_learning#33]
Hi @nwojke,

I am training on MARS and want to test the model export part. I am getting files in the output/mars/cosine-softmax/ like this:
- checkpoint                                 
- events.out.tfevents.1555681314.newdatapath  
- graph.pbtxt                                 
- model.ckpt-0.data-00000-of-00001            
- model.ckpt-80.data-00000-of-00001
- model.ckpt-161.data-00000-of-00001
- model.ckpt-0.index                          
- model.ckpt-80.index
- model.ckpt-161.index
- model.ckpt-0.meta                           
- model.ckpt-80.meta
- model.ckpt-161.meta

When I tried the command for model export using 

> python train_mars.py --mode=freeze --restore_path=output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001

It gave me the following errors. I am not sure if this caused by training (bad model data) or just about the exporting part. Thanks for your reply in advance.

> Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-04-19 10:00:09.059699: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-04-19 10:00:09.061005: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2019-04-19 10:00:09.061033: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[{{node save/RestoreV2}}]]

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "train_mars.py", line 119, in <module>
    main()
  File "train_mars.py", line 113, in main
    output_filename="./mars.pb")
  File "/data/xiaohui/2019/cosine_metric_learning/train_app.py", line 519, in freeze
    saver.restore(session, checkpoint_path)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at /data/xiaohui/2019/cosine_metric_learning/train_app.py:518) ]]

> Caused by op 'save/RestoreV2', defined at:
  File "train_mars.py", line 119, in <module>
    main()
  File "train_mars.py", line 113, in main
    output_filename="./mars.pb")
  File "/data/xiaohui/2019/cosine_metric_learning/train_app.py", line 518, in freeze
    saver = tf.train.Saver(slim.get_variables_to_restore())
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/xiaohui/.conda/envs/MASK/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

> DataLossError (see above for traceback): Unable to open table file output/mars/cosine-softmax/model.ckpt-161.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at /data/xiaohui/2019/cosine_metric_learning/train_app.py:518) ]]

**Comment by nwojke** [comment]
Hi CindyHXH,

can you try ``python train_mars.py --mode=freeze --restore_path=output/mars/cosine-softmax/model.ckpt-161`` to see if that works?

**Comment by CindyHXH** [comment]
Hi @nwojke,

Thank you very much. It worked. When I try `python train_mars.py --mode=freeze --restore_path=output/mars/cosine-softmax/model.ckpt-161`, I would have a `mars.pb`. The model export issue has been resolved.

However, I met issues when I was trying to use trained networks for deep_sort. I have used your `train_veri.py` and `veri.py` for training VeRi dataset. 
I noticed that in your folder `deep_sort/resources/networks/`, you have three files `mars-small128.ckpt-68577`, `mars-small128.ckpt-68577.meta` and `mars-small128.pb`.

After training, I have files such as `model.ckpt-21824.data-00000-of-00001`, `model.ckpt-21824.meta`, `model.ckpt-21824.index` and `veri.pd`. When I put them in the networks folder, changed related codes regarding filenames and run deepsort, it gives the following error

> ValueError: Checkpoint is missing variable [ball/beta]

Is this because I do not have a `model.ckpt-21824` file? How do I obtain a `model.ckpt-21824` such as your `mars-small128.ckpt-68577`? Thank you very much again.

**Comment by nwojke** [comment]
You should only need the protobuf (``.pb``) file when working with deep_sort code. If you didn't make any changes to ``deep_sort_app.py``, you need to generate detections after training the descriptor. The command is shown [here](https://github.com/nwojke/deep_sort#generating-detections). 

If you trained and exported your model with ``train_veri.py``, you should get a ``veri.pb``. Above you have used the ``train_mars.py`` script and I am not sure if this is just a typo. Anyways, using the ``veri.pb`` on MOT16 (doesn't really make sense but I don't know the layout of your own dataset), the command to generate detections would be

```
python tools/generate_detections.py \
    --model=resources/networks/veri.pb \
    --mot_dir=./MOT16/train \
    --output_dir=./resources/detections/MOT16_train_veri
```

**Comment by nwojke** [comment]
It is just an idea, but be aware that the script [tools/freeze_model.py](https://github.com/nwojke/deep_sort/blob/master/tools/freeze_model.py) in the deep_sort repository doesn't work with checkpoint files obtained from this repository.

**Comment by CindyHXH** [comment]
Hi @nwojke,

Thank you. After carefully checking the `generate_detections.py`, I found that I probably used an older version which has more than 400 lines. I changed to use your new deep_sort code and now I can get it working (with just `veri.pb.`). I really appreciate your help.

**Comment by nwojke** [comment]
That makes sense. The older version of that script was working with the checkpoint files instead of the frozen inference graph.
