### ISSUE TITLE
NewRandomAccessFile failed to Create/Open

### ISSUE THREAD

**Issue by noelcodes** [nwojke/cosine_metric_learning#46]
I can train without problem with mars dataset. But when I try on my own dataset, I hit into this error. I have tried to rename my images to be the same format as mars, not helping. Do you have any idea what did I do wrong?

```
(tripletloss) D:\xrv\XRV_projects\cosine_metric_learning>python train_mars.py --dataset_dir=./FR-dataset --loss_mode=cosine-softmax --log_dir=./output/FR/ --run_id=cosine-softmax
Train set size: 1537 images, 36 identities
feature dimensionality:  128
WARNING:tensorflow:From D:\xrv\XRV_projects\cosine_metric_learning\nets\deep_sort\network_definition.py:84: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
WARNING:tensorflow:From D:\xrv\XRV_projects\cosine_metric_learning\train_app.py:615: sparse_softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.sparse_softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
WARNING:tensorflow:From C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:434: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
WARNING:tensorflow:From C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:147: add_arg_scope.<locals>.func_with_args (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.add_loss instead.
---------------------------------------
Run ID:  cosine-softmax
Log directory:  ./output/FR/cosine-softmax
---------------------------------------
WARNING:tensorflow:From C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py:737: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2019-07-17 22:58:10.377791: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-07-17 22:58:10.559399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-07-17 22:58:10.570178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-17 22:58:11.103766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-17 22:58:11.110903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-07-17 22:58:11.114184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-07-17 22:58:11.117979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4722 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
ERROR: Failed to sample a full batch. Adding corrupt data.
2019-07-17 22:58:33.914975: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: NewRandomAccessFile failed to Create/Open:  : The system cannot find the path specified.
; No such process
EnqueueError: NewRandomAccessFile failed to Create/Open:  : The system cannot find the path specified.
; No such process
         [[node map/while/ReadFile (defined at D:\xrv\XRV_projects\cosine_metric_learning\train_app.py:250)  = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3)]]

Caused by op 'map/while/ReadFile', defined at:
  File "train_mars.py", line 119, in <module>
    main()
  File "train_mars.py", line 73, in main
    num_images_per_id=4, image_shape=IMAGE_SHAPE, **train_kwargs)
  File "D:\xrv\XRV_projects\cosine_metric_learning\train_app.py", line 188, in train_loop
    trainable_scopes=trainable_scopes)
  File "D:\xrv\XRV_projects\cosine_metric_learning\train_app.py", line 251, in create_trainer
    filename_var, back_prop=False, dtype=tf.uint8)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 494, in map_fn
    maximum_iterations=n)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3260, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 483, in compute
    packed_fn_values = fn(packed_values)
  File "D:\xrv\XRV_projects\cosine_metric_learning\train_app.py", line 250, in <lambda>
    tf.read_file(x), channels=num_channels),
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 531, in read_file
    "ReadFile", filename=filename, name=name)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): NewRandomAccessFile failed to Create/Open:  : The system cannot find the path specified.
; No such process
         [[node map/while/ReadFile (defined at D:\xrv\XRV_projects\cosine_metric_learning\train_app.py:250)  = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3)]]


(tripletloss) D:\xrv\XRV_projects\cosine_metric_learning>
```

**Comment by NaeemKhan333** [comment]
How you convert your own data to the same format as Mars data set format. Can you explain me please

**Comment by noelcodes** [comment]
Just a simple rename filenames to "looked" like the filename of mars, example 1586C4T1788F789.jpg. However, since my own dataset do not have camera_indices and tracklet_indices, this numbers in C,T,F are randomly generated, except for IDs. All images are organised in their own ID folders, so in the above related images, are stored in "1586" folder.

**Comment by nwojke** [comment]
I  haven't seen the error before, but ``The system cannot find the path specified.`` sounds a lot like it cannot find some (all?) of the files. Can you do a sanity check by iterating over the dataset and check if the files exist? The training script, before starting actual training should be a good location to do that.

**Comment by noelcodes** [comment]
Ya, I think its my path wrongly assigned, so above error disappeared. Now I have new error below. All I change in code are MAX_LABEL and IMAGE_SHAPE = 128, 128, 3. My images are mixture of png & jpg, size 128x128. Maybe there are more code to modify for custom dataset. Can u advise what to look out for if I use my own dataset?

```
(noel) D:\Noel\cosine_metric_learning>python train_mars.py  --dataset_dir=./FR_dataset --loss_mode=cosine-softmax --log_dir=./output/mars/  --run_id=cosine-softmax
Train set size: 30924 images, 587 identities
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py:162: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\keras\layers\core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
feature dimensionality:  128
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From D:\Noel\cosine_metric_learning\nets\deep_sort\network_definition.py:84: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
WARNING:tensorflow:From D:\Noel\cosine_metric_learning\train_app.py:615: sparse_softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.sparse_softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:406: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:103: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:151: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\losses\python\losses\loss_ops.py:120: add_arg_scope.<locals>.func_with_args (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.add_loss instead.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
---------------------------------------
Run ID:  cosine-softmax
Log directory:  ./output/mars/cosine-softmax
---------------------------------------
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py:737: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2019-07-20 10:33:46.168159: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-07-20 10:33:46.522363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:41:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2019-07-20 10:33:46.528947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-20 10:33:47.230905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-20 10:33:47.233293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-07-20 10:33:47.235305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-07-20 10:33:47.237658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6390 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:41:00.0, compute capability: 6.1)
2019-07-20 10:33:54.172208: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
2019-07-20 10:33:58.710803: E tensorflow/core/kernels/check_numerics_op.cc:185] abnormal_detected_host @0000001103405800 = {1, 0} LossTensor is inf or nan
2019-07-20 10:34:01.045432: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-07-20 10:34:01.049456: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-07-20 10:34:01.053975: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-07-20 10:34:01.059631: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[{{node train_op/CheckNumerics}}]]
         [[{{node train_op/control_dependency}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_mars.py", line 119, in <module>
    main()
  File "train_mars.py", line 73, in main
    num_images_per_id=4, image_shape=IMAGE_SHAPE, **train_kwargs)
  File "D:\Noel\cosine_metric_learning\train_app.py", line 199, in train_loop
    save_interval_secs=save_interval_secs, number_of_steps=number_of_steps)
  File "D:\Noel\cosine_metric_learning\queued_trainer.py", line 408, in run
    **kwargs)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 770, in train
    sess, train_op, global_step, train_step_kwargs)
  File "D:\Noel\cosine_metric_learning\queued_trainer.py", line 551, in _train_step_fn
    session, train_op, global_step, train_step_kwargs)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: LossTensor is inf or nan : Tensor had NaN values
         [[node train_op/CheckNumerics (defined at D:\Noel\cosine_metric_learning\train_app.py:286) ]]
         [[node train_op/control_dependency (defined at D:\Noel\cosine_metric_learning\train_app.py:286) ]]

Caused by op 'train_op/CheckNumerics', defined at:
  File "train_mars.py", line 119, in <module>
    main()
  File "train_mars.py", line 73, in main
    num_images_per_id=4, image_shape=IMAGE_SHAPE, **train_kwargs)
  File "D:\Noel\cosine_metric_learning\train_app.py", line 188, in train_loop
    trainable_scopes=trainable_scopes)
  File "D:\Noel\cosine_metric_learning\train_app.py", line 286, in create_trainer
    variables_to_train=variables_to_train)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 439, in create_train_op
    check_numerics=check_numerics)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\contrib\training\python\training\training.py", line 464, in create_train_op
    'LossTensor is inf or nan')
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 919, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\noel\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): LossTensor is inf or nan : Tensor had NaN values
         [[node train_op/CheckNumerics (defined at D:\Noel\cosine_metric_learning\train_app.py:286) ]]
         [[node train_op/control_dependency (defined at D:\Noel\cosine_metric_learning\train_app.py:286) ]]
```

**Comment by noelcodes** [comment]
AH...strange.. problem solved if I use tripletloss instead of cosine softmax. No more errors. I read your papers, tripletloss seems getting almost the same result, I'm fine to stay tripletloss. I'm just curious why I cannot use cosine-softmax. If u have an idea, pls advise, else I think this thread can be close. Thank you so much.

**Comment by nwojke** [comment]
Strange, a NaN or Inf in your training loss but no issues with triplet... I would double check the labels against number of classes since it is specific the softmax loss. Another explanation would be that your logits are very large in magnitude, causing numerical issues.

Edit: As you said, I think you should be fine with the triplet if that works for you.

**Comment by nwojke** [comment]
I close the issue since the problems seems fixed to you, but let me know if you investigate further.
